title = "Aleksandr Tihomirov"
baseURL = "https://zeta.pm"
tags = ["portfolio", "golang", "blog"]
languageCode = "en-us"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-37091239-1"
disqusShortname = "zetasblog"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    tagline = "Aleksandr Tihomirov"
    author = "Aleksandr Tihomirov"
    description = "Golang backend developer and Cloud enthusiast based in Europe. I enjoy using multiple tools to engineer and build powerful websites and apps."
    authorimage = "/images/gopher.png"
    logoBig = "/images/gopher.png"
    logoSmall = "/images/gopher.png"
    dateformat = "Jan 2, 2006"
    intro = "Gopher, Blogger & Cloud Enthusiast"
    favicon = "favicon.ico"
    opengraphImage = "/images/gopher.png"
    email = "me@zeta.pm"
    github = "zet4"
    linkedin = "aleksandrtihomirov"
    twitter = "ZetaFoxgirl"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[permalinks]
    gallery = "/" # Redirect gallery index to home page
[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
[[menu.main]]
    identifier = "discord"
    name = "discord"
    url = "https://discord.gg/h5Aegcr"
    weight = 5
