baseURL = "https://zeta.pm"
canonifyURLS = true
config = "config.toml"
disableKinds = ["taxonomy", "taxonomyTerm"]
disqusShortname = "zetasblog"
googleAnalytics = "UA-37091239-1"
languageCode = "en-us"
tags = ["portfolio", "golang", "blog"]
theme = "osprey-fork"
title = "Aleksandr Tihomirov"
[[menu.main]]
name = "Contact"
url = "/#contact"
weight = 4
[[menu.main]]
name = "Blog"
url = "/#blog"
weight = 3
[[menu.main]]
name = "Work"
url = "/#work"
weight = 2
[[menu.main]]
name = "About"
url = "/#about"
weight = 1
[params]
ajaxformspree = true
author = "Aleksandr Tihomirov"
authorimage = "/images/gopher.png"
cachebustcss = false
cachebustjs = false
copyright = true
credit = true
customcss = false
dateformat = "Jan 2, 2006"
description = "Golang backend developer and Cloud enthusiast based in Europe. I enjoy using multiple tools to engineer and build powerful websites and apps."
email = "me@zeta.pm"
favicon = "favicon.ico"
github = "zet4"
googletagmanager = ""
highlightjs = true
intro = "Gopher, Blogger & Cloud Enthusiast"
keybase = "zeta"
linkedin = "aleksandrtihomirov"
logobig = "/images/gopher.png"
logosmall = "/images/gopher.png"
opengraphimage = "/images/gopher.png"
tagline = "Aleksandr Tihomirov"
twitter = "Zet4Codes"
[permalinks]
gallery = "/"
